name: 🧪 Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  web-deploy:
    name: Deploying to Staging Server

    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files to Staging
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_TEST_SERVER }}
          username: ${{ secrets.FTP_TEST_USERNAME }}
          password: ${{ secrets.FTP_TEST_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR_STAGING }}
